<Project>
  <PropertyGroup>
    <Version>1.4.0</Version>
    <Product>AnyPortProxy</Product>
    <Company>AnyPortProxy</Company>
    <Copyright>AnyPortProxy</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
</Project>
